version: 0.0
os: linux
files:
   - source: /
     destination: /var/www/html
permissions:
   - object: /var/www/html
     pattern: "**"
     owner: ubuntu
     group: ubuntu
     mode: 755
     type:
       - file
hooks:
   BeforeInstall:
    - location: scripts/installapache
      runas: ubuntu
    - location: scripts/startapache.sh
      runas: ubuntu
   AfterInstall:
    - location: scripts/restartapache.sh
      runas: ubuntu