#!/bin/bash
# Set permissions to storage and bootstrap cache
sudo chmod -R 0777 /var/www/html/storage
sudo chmod -R 0777 /var/www/html/bootstrap/cache

cd /var/www/html/laravel/
composer install 
cp .env.example .env 
php artisan key:generate 



