#!/bin/bash
# Set permissions to storage and bootstrap cache
sudo chmod -R 0777 /var/www/html/storage
sudo chmod -R 0777 /var/www/html/bootstrap/cache

cd /var/www/html/laravel/
composer install 
aws s3 cp s3://ubuntu-deploy-app-resources/database_config config
cp config .env 
php artisan key:generate 
php artisan migrate


